drivers/usb/gadget/function: Try to fix missing read_spinlock variable
../drivers/usb/gadget/function/f_hid.c:511:27: error: no member named 'read_spinlock' in 'struct f_hidg'
        spin_lock_irqsave(&hidg->read_spinlock, flags);
                           ~~~~  ^
../include/linux/spinlock.h:337:39: note: expanded from macro 'spin_lock_irqsave'
        raw_spin_lock_irqsave(spinlock_check(lock), flags);     \
                                             ^~~~
../include/linux/spinlock.h:208:34: note: expanded from macro 'raw_spin_lock_irqsave'
                flags = _raw_spin_lock_irqsave(lock);   \
                                               ^~~~
../drivers/usb/gadget/function/f_hid.c:517:32: error: no member named 'read_spinlock' in 'struct f_hidg'
        spin_unlock_irqrestore(&hidg->read_spinlock, flags);

Import Chatur fix for USB gadget (Thanks!)
Github profile: https://github.com/Chatur27
Repo: https://github.com/Chatur27/Parad0x-Kernel
Branch: patch-1
Commit: https://github.com/Chatur27/Parad0x-Kernel/commit/5c68cc66bb3d2a51c56f3356a60d77b14181204e